// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20251019181124_AddMoreSeedData")]
    partial class AddMoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96210f93-0139-4467-873b-248356980e14"),
                            IsDone = true,
                            Title = "Learn Blazor"
                        },
                        new
                        {
                            Id = new Guid("468d6f93-0239-4981-8b7a-e390c427301c"),
                            IsDone = false,
                            Title = "Build this Todo App"
                        },
                        new
                        {
                            Id = new Guid("c3f0c2a2-4a0b-4652-9e6b-a15d045d44cc"),
                            IsDone = false,
                            Title = "Deploy to Azure"
                        },
                        new
                        {
                            Id = new Guid("d147a4c5-031f-431e-b81b-5f09673994c1"),
                            IsDone = false,
                            Title = "Configure Tailwind CSS"
                        },
                        new
                        {
                            Id = new Guid("4b12c6a0-e6f8-4e89-8b83-2d939e6a0d4c"),
                            IsDone = false,
                            Title = "Design the main Blazor component"
                        },
                        new
                        {
                            Id = new Guid("5c69b2d8-21f4-4a7b-a0f1-41712c4b7b3b"),
                            IsDone = true,
                            Title = "Write unit tests for TodoService"
                        },
                        new
                        {
                            Id = new Guid("8e20f0e3-3e1c-4b3f-8a0a-0402e6002f2d"),
                            IsDone = false,
                            Title = "Set up CI/CD pipeline"
                        },
                        new
                        {
                            Id = new Guid("f67c3b9a-4d7a-4c2b-b8f3-490f84a5e3c7"),
                            IsDone = true,
                            Title = "Read documentation on C# 12 features"
                        },
                        new
                        {
                            Id = new Guid("1a58c1f0-58d3-4e6a-8d7e-0730b2e8a1f4"),
                            IsDone = true,
                            Title = "Refactor existing application services"
                        },
                        new
                        {
                            Id = new Guid("6e0c7e2d-6b1a-4c9f-8d2b-67a3f81e7d0a"),
                            IsDone = false,
                            Title = "Implement drag-and-drop for task ordering"
                        },
                        new
                        {
                            Id = new Guid("c9f0d1a4-7a3b-4e5c-9d4e-18f6c4d7b9e0"),
                            IsDone = false,
                            Title = "Review pull requests from teammates"
                        },
                        new
                        {
                            Id = new Guid("7d2e8b0a-8c9d-4e1f-a3b0-27c5e9f8a1d2"),
                            IsDone = true,
                            Title = "Create a database backup script"
                        },
                        new
                        {
                            Id = new Guid("4b5c6d7e-9f0a-4b1c-8e2d-3a4f5b6c7d8e"),
                            IsDone = false,
                            Title = "Research state management alternatives (e.g., Flux)"
                        },
                        new
                        {
                            Id = new Guid("2f9e4d1c-a0b1-4c3e-9d5f-4b6c7d8e9f0a"),
                            IsDone = true,
                            Title = "Attend the morning stand-up meeting"
                        },
                        new
                        {
                            Id = new Guid("3a8b4c5d-b1c2-4e6f-9d7a-5f8b9c0d1e2f"),
                            IsDone = false,
                            Title = "Fix critical bug in authentication module"
                        },
                        new
                        {
                            Id = new Guid("5c7d8e9f-c2d3-4f0a-a1b2-6e9f0a1b2c3d"),
                            IsDone = false,
                            Title = "Write documentation for new API endpoint"
                        },
                        new
                        {
                            Id = new Guid("7e9f0a1b-d3e4-4c2d-b8a3-7f0a1b2c3d4e"),
                            IsDone = true,
                            Title = "Configure logging to Azure Application Insights"
                        },
                        new
                        {
                            Id = new Guid("8f0a1b2c-e4f5-4d3e-c9b0-8a1b2c3d4e5f"),
                            IsDone = false,
                            Title = "Test responsive layout on mobile devices"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-f5a6-4e5c-9d6e-9b2c3d4e5f6a"),
                            IsDone = true,
                            Title = "Optimize database queries for performance"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c6d-b8e7-a1d2e3f4a5b6"),
                            IsDone = true,
                            Title = "Prepare presentation for team meeting"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e7f-a0b1-b2c3d4e5f6a7"),
                            IsDone = false,
                            Title = "Set up git hooks for automatic formatting"
                        },
                        new
                        {
                            Id = new Guid("0d1e2f3a-d0e1-4f8a-9b1c-c3d4e5f6a7b8"),
                            IsDone = false,
                            Title = "Order new monitors for the development team"
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-e1f2-4e9f-a2c3-d4e5f6a7b8c9"),
                            IsDone = true,
                            Title = "Review security policy documentation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
